- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 192.168.99.10 zabbix zabbix.dexter.com.br
        - 192.168.99.11 prometheus prometheus.dexter.com.br
        - 192.168.99.12 4flix 4flix.dexter.com.br
        - 192.168.99.13 graylog graylog.dexter.com.br

    - name: Configura hostname da VM
      hostname:
        name: 4flix

    - name: Instalando pacotes de dependencias para o curso
      yum:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - epel-release
        - policycoreutils-python-utils
        - git
        - net-tools
        - java-1.8.0-openjdk

    - name: Criando diret√≥rio apache-jmeter
      synchronize:
        src: files/apache-jmeter-5.2
        dest: /root

    - name: Download do repositorio do Jenkins
      get_url:
        url: https://pkg.jenkins.io/redhat/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        validate_certs: False
      become: true

    - name: Importar chave GPG do Jenkins
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat/jenkins.io.key
        validate_certs: False

    - name: Instalar o Jenkins
      yum:
        name: jenkins
        state: present

    - name: Iniciar servico do Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Criando o arquivo sudo para o usuario jenkins
      copy:
        src: files/jenkins
        dest: /etc/sudoers.d
        mode: 0644

    - name: Criando o arquivo mongodb-org-3.6.repo
      copy:
        src: files/mongodb-org-3.6.repo
        dest: /etc/yum.repos.d
        mode: 0644

    - name: Instalar o mongodb-org-shell
      yum:
        name: mongodb-org-shell.x86_64
        state: present

    - name: Atualiza o timezone
      shell: timedatectl set-timezone America/Sao_Paulo
      args:
