---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 192.168.99.10 zabbix zabbix.dexter.com.br
        - 192.168.99.11 prometheus prometheus.dexter.com.br
        - 192.168.99.12 4flix 4flix.dexter.com.br
        - 192.168.99.13 graylog graylog.dexter.com.br

    - name: Adicionar usuario suporte
      user:
        name: suporte
        shell: /bin/bash
        password : $1$QbUARykG$p2nthVG8AkDvabKPHwboa1

    - name: Criando o arquivo 98_4linux
      copy:
        src: files/98_4linux
        dest: /etc/sudoers.d
        mode: 0644

    - name: Ajustando .bashrc do usuario vagrant
      lineinfile:
        path: /home/vagrant/.bashrc
        line: 'sudo su - suporte'

    - name: Instalando pacotes de dependencias para o curso
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - unzip
        - python3
        - python3-pip
        - software-properties-common
        update_cache: yes
        
    - name: Criando o arquivo get-pip.py
      copy:
        src: files/get-pip.py
        dest: /tmp
        mode: 0644

    - name: Criando o arquivo get-pip.py
      copy:
        src: files/get-pip.py
        dest: /tmp
        mode: 0644

    - name: Atualiza o pip com Python 3
      shell: python3 get-pip.py
      args:
        chdir: /tmp
