---
- name: zabbix
  box: trombik/ansible-ubuntu-18.04-amd64
  hostname: zabbix.dexter.com.br
  ipaddress: 192.168.99.10
  memory: 1536
  cpus: 1
  provision: provision/ansible/zabbix.yaml

- name: prometheus
  box: trombik/ansible-centos-7.3-x86_64
  hostname: prometheus.dexter.com.br
  ipaddress: 192.168.99.11
  memory: 1536
  cpus: 1
  provision: provision/ansible/prometheus.yaml

- name: 4flix
  box: trombik/ansible-centos-7.3-x86_64
  hostname: 4flix.dexter.com.br
  ipaddress: 192.168.99.12
  memory: 2048
  cpus: 1
  provision: provision/ansible/4flix.yaml

- name: graylog
  box: trombik/ansible-ubuntu-18.04-amd64
  hostname: graylog.dexter.com.br
  ipaddress: 192.168.99.13
  memory: 2048
  cpus: 1
  provision: provision/ansible/graylog.yaml
